<?php
$baseurl = "https://";
$baseurl.= $_SERVER['SERVER_NAME'];
$baseurl.= $this->baseUrl();
$baseurl.= "/";
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- Default URL  -->
    <base href="<?php echo $baseurl; ?>" />
    <?php echo $this->headTitle('Manager Pago Facil'); ?><?php echo "\r\n"; ?>
    <?php echo $this->headScript()->appendFile('js/jquery-1.8.0.min.js')
        ->appendFile('js/registro.js');
    ?><?php echo "\r\n"; ?>

    ?><?php echo "\r\n"; ?>
</head>
<body>
<div id="wrapperLogin">
    <div id="content">
        <?php echo $this->layout()->content ?>
    </div>
</div>
</body>
</html>