<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- Default URL  -->
    <base href = "<?php echo $this->baseUrl(); ?>" />
    <?php echo $this->headMeta()->appendHttpEquiv( 'Content-Type', 'text/html; charset=UTF-8' ); ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/offline.css"/>

    <!-- javascript -->
    <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.js'); ?>
</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>
